# This will be the first part of the title tag for your site <title> site.name + page.title </title>
name: Devan Huapaya

# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
description: "Personal website of super awesome front end developer unicorn person, Devannnnn Huapaya!"

# Owner (organization or individual) of site content
author: Devan Huapaya

#url: "[http:// ]"
url: "http://imdevan.github.io"
baseurl: "http://0.0.0.0:8080"

markdown: kramdown

kramdown:
    input: GFM

# Pagination variable for how many posts to show in a list
paginate: 30
post_dirs: false


# Style of permalinks
permalink: /:categories/:title/

collections:
    projects:
        output: true
        permalink: /projects/:path/

gems: ['jekyll-sitemap', 'jekyll-paginate']

exclude: [node_modules, Gruntfile.js, package.json]
