# Site Config

name: "imdevan"
description: >
    I'm a freelance developer. I write javascript and build things for the internet.
baseurl: "http://imdevan.com"
url: http://imdevan.com
slug: imdevan
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - kramdown
  - rouge
  - jekyll-time-to-read

image: http://i.imgur.com/vkFkFqk.png
# Markdown settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

# Pagination variable for how many posts to show in a list
paginate: 30
post_dirs: false

# Style of permalinks
permalink: /:categories/:title/


# In/excludes
include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json", "local_config.yml"]

# Plugins
assets:
  digest: true
  cache: false
  sources:
    - "assets/css"
    - "images"

# Read and Output Collections
collections:
  projects:
    output: true
    permalink: /portfolio/:title/
