# Site Config

name: "Terminalogy"
description: A list of commonly used commands and aliases for your terminal.
baseurl: "/terminalogy"
url: https://matthewcpaul.github.io/terminalogy

# Build Settings

markdown: kramdown

highlighter: true

permalink: pretty

# In/excludes

include: [".htaccess"]
exclude: ["node_modules", "gulpfile.js", "Gemfile", "Gemfile.lock", ".jekyll-metadata", "commit-hook.sh", "package.json"]

# Plugins

assets:
  digest: true
  cache: false
  sources:
    - "_assets/css"
    - "images"

# Read and Output Collections

collections:
  commands:
    output: false
